# Generated by Django 5.0.3 on 2024-03-29 10:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=30)),
                ('invoice_number', models.IntegerField(unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('shipping_address', models.CharField(max_length=150)),
                ('billing_address', models.CharField(max_length=150)),
                ('gstin', models.CharField(max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('invoice_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.invoicemaster')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceBillSundry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bill_sundry_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('invoice_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.invoicemaster')),
            ],
        ),
    ]
